version: '3.8'

volumes:
  employee-data:

networks:
  employee-net:

services:
  employee-app:
    image: kuriankevin20/employee-app:1.0.0
    environment:
      - DB_HOST=employee-db
      - THIRD_MESSAGE=Docker-Compose Message
    ports:
      - 8080:8080
    networks:
      - employee-net
    restart: on-failure

  employee-db:
    image: mysql:8.0.27
    environment:
      - MYSQL_DATABASE=employee_db
      - MYSQL_USER=employee
      - MYSQL_PASSWORD=employee
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - employee-data:/var/lib/mysql
    networks:
      - employee-net
