apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  employee-schema: {{ .Values.configMapValue.employeeSchema }}
  third-message: {{ .Values.configMapValue.thirdMessage }}