apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-db-deployment
  labels:
    app: employee-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-db
  template:
    metadata:
      labels:
        app: employee-db
    spec:
      containers:
      - name: employee-db
        image: mysql:8.0.27
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: employee-schema
        - name: MYSQL_USER
          valueFrom: 
            secretKeyRef:
              name: app-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: mysql-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: mysql-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: employee-db-service
spec:
  selector:
    app: employee-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
