apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app-deployment
  labels:
    app: employee-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
      - name: employee-app
        image: kuriankevin20/employee-app:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: employee-db-service
---
apiVersion: v1
kind: Service
metadata:
  name: employee-app-service
spec:
  selector:
    app: employee-app
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
